# Generated by Django 3.0.8 on 2020-08-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_userblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='images',
            field=models.ImageField(blank=True, upload_to='portfolio/images/'),
        ),
    ]
